// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3T4omZ2TGYwyLPTv0F0jzgPb4PnAcjvI',
    appId: '1:589220994069:web:ff05684a6cd69f3512421c',
    messagingSenderId: '589220994069',
    projectId: 'deltaexplorer-7c080',
    authDomain: 'deltaexplorer-7c080.firebaseapp.com',
    storageBucket: 'deltaexplorer-7c080.firebasestorage.app',
    measurementId: 'G-N48ZC7L9B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVqLFDyjEIn83IZHn26JJgRiVd4kNyzw',
    appId: '1:589220994069:android:49229a8e817525bf12421c',
    messagingSenderId: '589220994069',
    projectId: 'deltaexplorer-7c080',
    storageBucket: 'deltaexplorer-7c080.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANacXdRQ6BVzPfVDjd4PRgf9kJjWJGVeE',
    appId: '1:589220994069:ios:6b5b29522b2b130c12421c',
    messagingSenderId: '589220994069',
    projectId: 'deltaexplorer-7c080',
    storageBucket: 'deltaexplorer-7c080.firebasestorage.app',
    iosBundleId: 'com.example.deltaExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANacXdRQ6BVzPfVDjd4PRgf9kJjWJGVeE',
    appId: '1:589220994069:ios:6b5b29522b2b130c12421c',
    messagingSenderId: '589220994069',
    projectId: 'deltaexplorer-7c080',
    storageBucket: 'deltaexplorer-7c080.firebasestorage.app',
    iosBundleId: 'com.example.deltaExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3T4omZ2TGYwyLPTv0F0jzgPb4PnAcjvI',
    appId: '1:589220994069:web:3266865692de1c1d12421c',
    messagingSenderId: '589220994069',
    projectId: 'deltaexplorer-7c080',
    authDomain: 'deltaexplorer-7c080.firebaseapp.com',
    storageBucket: 'deltaexplorer-7c080.firebasestorage.app',
    measurementId: 'G-8G6J938TCZ',
  );

}